# Generated by Django 2.1.5 on 2019-03-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='new_normaluser',
        ),
    ]
